# Generated by Django 5.0 on 2024-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_material',
            field=models.FileField(blank=True, default=None, null=True, upload_to='study_materials/'),
        ),
    ]
