# Generated by Django 5.0 on 2024-05-05 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_course_study_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='study_material',
            field=models.FileField(blank=True, default=django.utils.timezone.now, null=True, upload_to='study_materials/'),
        ),
    ]
