# Generated by Django 5.0.4 on 2024-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial_thumbnails'),
        ),
    ]
