# Generated by Django 5.0 on 2024-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tutorial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='module_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
