# Generated by Django 5.0 on 2024-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_tutorial_module_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='module_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
