# Generated by Django 5.0.4 on 2024-05-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_courses',
        ),
        migrations.CreateModel(
            name='UserCourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'course')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchased_courses',
            field=models.ManyToManyField(through='accounts.UserCourseRelation', to='store.course'),
        ),
    ]
