# Generated by Django 5.0.4 on 2024-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_selected_courses_and_more'),
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='purchased_courses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_courses',
            field=models.ManyToManyField(to='store.course'),
        ),
        migrations.DeleteModel(
            name='UserCourseRelation',
        ),
    ]
