# Generated by Django 5.0.4 on 2024-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default_category_image.jpg', upload_to='category/'),
        ),
    ]
